version: '3.8'

services:
  incidentflow-postgres:
    image: postgres:16-alpine
    container_name: incidentflow-postgres
    environment:
      POSTGRES_DB: IncidentFlow_db
      POSTGRES_USER: IncidentFlow_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - incidentflow-network
    restart: unless-stopped

  incidentflow-keycloak:
    image: keycloak/keycloak:21.1.1
    container_name: incidentflow-keycloak
    command: start-dev --import-realms
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KC_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://incidentflow-postgres:5432/IncidentFlow_db
      KC_DB_USERNAME: IncidentFlow_user
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8180:8080"
    depends_on:
      - incidentflow-postgres
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
    networks:
      - incidentflow-network
    restart: unless-stopped

  incidentflow-redis:
    image: redis:7-alpine
    container_name: incidentflow-redis
    ports:
      - "6380:6379"
    networks:
      - incidentflow-network
    restart: unless-stopped

  incidentflow-backend:
    build: ./backend
    container_name: incidentflow-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://incidentflow-postgres:5432/IncidentFlow_db
      SPRING_DATASOURCE_USERNAME: IncidentFlow_user
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_PROFILES_ACTIVE: dev-mock
      SPRING_DATA_REDIS_HOST: incidentflow-redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    depends_on:
      - incidentflow-postgres
      - incidentflow-redis
    networks:
      - incidentflow-network
    restart: unless-stopped

  # incidentflow-frontend:
  #   build: ./frontend
  #   container_name: incidentflow-frontend
  #   environment:
  #     REACT_APP_API_URL: http://incidentflow-backend:8080
  #     REACT_APP_KEYCLOAK_URL: http://incidentflow-keycloak:8080
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - incidentflow-backend
  #   networks:
  #     - incidentflow-network
  #   restart: unless-stopped

volumes:
  postgres-data:

networks:
  incidentflow-network:
    driver: bridge
